# Site settings
title: Päiväkoti Omenapuu
email: omenapuu.web@gmail.com
description: >-
  Päiväkoti Omenapuu on pieni, kodinomainen ja lämminhenkinen
  vanhenpainyhdistyksen ylläpitämä päiväkoti, joka sijaitsee luonnonkauniissa ympäristössä
  Mäntsälän Mäntymäentiellä.
domain: paivakotiomenapuu.github.io
url: https://paivakotiomenapuu.github.io
baseurl: ""

# Variables
sections:
  - name: Omppu
    link: "#about"
  - name: Arvot
    link: "#values"
  - name: Ryhmät
    link: "#groups"
  - name: Yhteystiedot
    link: "#contact"

values:
  - icon: bi-award
    title: Lorep ipsum
    description: Maecenas tincidunt egestas lacus, sed viverra est eleifend et.
  - icon: bi-joystick
    title: Lorep ipsum
    description: Maecenas tincidunt egestas lacus, sed viverra est eleifend et.
  - icon: bi-globe-americas
    title: Lorep ipsum
    description: Maecenas tincidunt egestas lacus, sed viverra est eleifend et.
  - icon: bi-heart
    title: Lorep ipsum
    description: Maecenas tincidunt egestas lacus, sed viverra est eleifend et.

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-webp

# WebP Generator Plugin
webp:
  enabled: true
  img_dir: ["/assets/img"]
