source "https://rubygems.org"

gem "webrick"
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "github-pages"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-minifier"
  gem "jekyll-webp"
  gem "jekyll-admin"
end


